CREATE TABLE PASS_CLASS(
    PASS_CLASS_ID IDENTITY PRIMARY KEY,
    PASS_CLASS_NAME VARCHAR2(50) NOT NULL UNIQUE,
    PASS_CLASS_DESC VARCHAR2(100),
    CREATE_DATE DATETIME NOT NULL DEFAULT NOW()
);

CREATE TABLE RULE(
    RULE_ID IDENTITY PRIMARY KEY,
    RULE_NAME VARCHAR2(50) NOT NULL UNIQUE,
    RULE_DESC VARCHAR2(100),
    RULE_VALUE_TYPE VARCHAR2(20),
    REJECT_MESSAGE VARCHAR2(50) NOT NULL,
    CREATE_DATE DATETIME NOT NULL DEFAULT NOW(),

    CHECK(RULE_VALUE_TYPE IN('INTEGER','STRING'))
);

CREATE TABLE CLASS_RULE(
    CLASS_RULE_ID IDENTITY PRIMARY KEY,
    PASS_CLASS_ID BIGINT NOT NULL,
    RULE_ID BIGINT NOT NULL,
    RULE_VALUE VARCHAR2(50),
    RULE_ORDER INT NOT NULL,
    CREATE_DATE DATETIME NOT NULL DEFAULT NOW(),

    FOREIGN KEY(PASS_CLASS_ID) REFERENCES PASS_CLASS(PASS_CLASS_ID),
    FOREIGN KEY(RULE_ID) REFERENCES RULE(RULE_ID)
);