INSERT INTO PASS_CLASS(PASS_CLASS_NAME, PASS_CLASS_DESC)
VALUES('NCPWR', 'Nine Chars Password Without Repetition');

INSERT INTO RULE(RULE_NAME, RULE_DESC, RULE_VALUE_TYPE, REJECT_MESSAGE)
VALUES
('MIN_PASS_SIZE', 'Minimum password size', 'INTEGER', 'Tamanho mínimo da senha: %s caracteres'),
('MAX_PASS_SIZE', 'Maximum password size', 'INTEGER', 'Tamanho máximo da senha: %s caracteres'),
('MIN_DIGIT_OCCURRENCES', 'Minimum number of digits', 'INTEGER', 'Número mínimo de dígitos: %s'),
('MIN_LOWERCASE_CHARS', 'Minimum number of lowercase characters', 'INTEGER', 'Número mínimo de letras minúsculas: %s'),
('MIN_UPPERCASE_CHARS', 'Minimum number of uppercase characters', 'INTEGER', 'Número mínimo de letras maiúsculas: %s'),
('MIN_SPECIAL_CHARS', 'Minimum number of special characters', 'INTEGER', 'Número mínimo de caracteres especiais: %s'),
('NO_REPEATED_CHARS', 'Repeated characters not allowed', null, 'Não são permitidos caracteres repetidos');

INSERT INTO CLASS_RULE(PASS_CLASS_ID, RULE_ID, RULE_VALUE, RULE_ORDER)
VALUES((SELECT PASS_CLASS_ID FROM PASS_CLASS WHERE PASS_CLASS_NAME='NCPWR'), (SELECT RULE_ID FROM RULE WHERE RULE_NAME='MIN_PASS_SIZE'), '9', 1);

INSERT INTO CLASS_RULE(PASS_CLASS_ID, RULE_ID, RULE_VALUE, RULE_ORDER)
VALUES((SELECT PASS_CLASS_ID FROM PASS_CLASS WHERE PASS_CLASS_NAME='NCPWR'), (SELECT RULE_ID FROM RULE WHERE RULE_NAME='MAX_PASS_SIZE'), '20', 2);

INSERT INTO CLASS_RULE(PASS_CLASS_ID, RULE_ID, RULE_VALUE, RULE_ORDER)
VALUES((SELECT PASS_CLASS_ID FROM PASS_CLASS WHERE PASS_CLASS_NAME='NCPWR'), (SELECT RULE_ID FROM RULE WHERE RULE_NAME='MIN_DIGIT_OCCURRENCES'), '1', 3);

INSERT INTO CLASS_RULE(PASS_CLASS_ID, RULE_ID, RULE_VALUE, RULE_ORDER)
VALUES((SELECT PASS_CLASS_ID FROM PASS_CLASS WHERE PASS_CLASS_NAME='NCPWR'), (SELECT RULE_ID FROM RULE WHERE RULE_NAME='MIN_LOWERCASE_CHARS'), '1', 4);

INSERT INTO CLASS_RULE(PASS_CLASS_ID, RULE_ID, RULE_VALUE, RULE_ORDER)
VALUES((SELECT PASS_CLASS_ID FROM PASS_CLASS WHERE PASS_CLASS_NAME='NCPWR'), (SELECT RULE_ID FROM RULE WHERE RULE_NAME='MIN_UPPERCASE_CHARS'), '1', 5);

INSERT INTO CLASS_RULE(PASS_CLASS_ID, RULE_ID, RULE_VALUE, RULE_ORDER)
VALUES((SELECT PASS_CLASS_ID FROM PASS_CLASS WHERE PASS_CLASS_NAME='NCPWR'), (SELECT RULE_ID FROM RULE WHERE RULE_NAME='MIN_SPECIAL_CHARS'), '1', 6);

INSERT INTO CLASS_RULE(PASS_CLASS_ID, RULE_ID, RULE_ORDER)
VALUES((SELECT PASS_CLASS_ID FROM PASS_CLASS WHERE PASS_CLASS_NAME='NCPWR'), (SELECT RULE_ID FROM RULE WHERE RULE_NAME='NO_REPEATED_CHARS'), 7);

COMMIT;